01-25 19:53:31 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table RENAME not found; SQL statement: alter table rename user to usertbl [42S02-34]
	at org.h2.message.Message.addSQL(Message.java:341)
	at org.h2.command.Parser.parse(Parser.java:224)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:169)
	at org.h2.engine.Session.prepareCommand(Session.java:151)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:170)
	at zigen.plugin.db.ui.jobs.SqlJob.executeUpdate(SqlJob.java:111)
	at zigen.plugin.db.ui.jobs.SqlJob.executeSingleSQL(SqlJob.java:79)
	at zigen.plugin.db.ui.jobs.SqlJob.run(SqlJob.java:40)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)
org.h2.jdbc.JdbcSQLException: Table RENAME not found [42S02-34]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.schema.Schema.getTableOrView(Schema.java:199)
	at org.h2.command.Parser.parseAlterTable(Parser.java:3475)
	at org.h2.command.Parser.parseAlter(Parser.java:3173)
	at org.h2.command.Parser.parse(Parser.java:258)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:169)
	at org.h2.engine.Session.prepareCommand(Session.java:151)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at zigen.plugin.db.core.SQLInvoker.executeUpdate(SQLInvoker.java:170)
	at zigen.plugin.db.ui.jobs.SqlJob.executeUpdate(SqlJob.java:111)
	at zigen.plugin.db.ui.jobs.SqlJob.executeSingleSQL(SqlJob.java:79)
	at zigen.plugin.db.ui.jobs.SqlJob.run(SqlJob.java:40)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)
01-25 19:54:12 database: opening C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\jeeTa\startup\db\sel
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-34]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:136)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:95)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:85)
	at org.seasar.extension.dbcp.impl.ConnectionPoolImpl.createConnection(ConnectionPoolImpl.java:200)
	at org.seasar.extension.dbcp.impl.ConnectionPoolImpl.checkOut(ConnectionPoolImpl.java:162)
	at org.seasar.extension.dbcp.impl.DataSourceImpl.getConnection(DataSourceImpl.java:46)
	at org.seasar.extension.jdbc.util.DataSourceUtil.getConnection(DataSourceUtil.java:36)
	at org.seasar.dao.impl.DaoMetaDataImpl.initialize(DaoMetaDataImpl.java:191)
	at org.seasar.dao.impl.DaoMetaDataFactoryImpl.createDaoMetaData(DaoMetaDataFactoryImpl.java:140)
	at org.seasar.dao.impl.DaoMetaDataFactoryImpl.getDaoMetaData(DaoMetaDataFactoryImpl.java:109)
	at org.seasar.dao.interceptors.S2DaoInterceptor.invoke(S2DaoInterceptor.java:51)
	at sel.dao.DocDao$$EnhancedByS2AOP$$3e89c3$$MethodInvocation$$findByDocTypeId0.proceed(MethodInvocationClassGenerator.java)
	at sel.dao.DocDao$$EnhancedByS2AOP$$3e89c3.findByDocTypeId(DocDao$$EnhancedByS2AOP$$3e89c3.java)
	at sel.model.DocModel.initialize(DocModel.java:51)
	at sel.view.MainView.setup(MainView.java:1394)
	at sel.Main.newMainView(Main.java:23)
	at sel.Main$2.execute(Main.java:57)
	at sel.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
01-25 19:54:36 database: opening C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\jeeTa\startup\db\sel
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-34]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:136)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:95)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:85)
	at org.seasar.extension.dbcp.impl.ConnectionPoolImpl.createConnection(ConnectionPoolImpl.java:200)
	at org.seasar.extension.dbcp.impl.ConnectionPoolImpl.checkOut(ConnectionPoolImpl.java:162)
	at org.seasar.extension.dbcp.impl.DataSourceImpl.getConnection(DataSourceImpl.java:46)
	at org.seasar.extension.jdbc.util.DataSourceUtil.getConnection(DataSourceUtil.java:36)
	at org.seasar.dao.impl.DaoMetaDataImpl.initialize(DaoMetaDataImpl.java:191)
	at org.seasar.dao.impl.DaoMetaDataFactoryImpl.createDaoMetaData(DaoMetaDataFactoryImpl.java:140)
	at org.seasar.dao.impl.DaoMetaDataFactoryImpl.getDaoMetaData(DaoMetaDataFactoryImpl.java:109)
	at org.seasar.dao.interceptors.S2DaoInterceptor.invoke(S2DaoInterceptor.java:51)
	at sel.dao.DocDao$$EnhancedByS2AOP$$3e89c3$$MethodInvocation$$findByDocTypeId0.proceed(MethodInvocationClassGenerator.java)
	at sel.dao.DocDao$$EnhancedByS2AOP$$3e89c3.findByDocTypeId(DocDao$$EnhancedByS2AOP$$3e89c3.java)
	at sel.model.DocModel.initialize(DocModel.java:51)
	at sel.view.MainView.setup(MainView.java:1394)
	at sel.Main.newMainView(Main.java:23)
	at sel.Main$2.execute(Main.java:57)
	at sel.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
01-28 01:28:32 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Timeout trying to lock table DOC [HYT00-34]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.table.TableData.lock(TableData.java:311)
	at org.h2.table.TableFilter.lock(TableFilter.java:72)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:320)
	at org.h2.command.dml.Query.query(Query.java:91)
	at org.h2.command.CommandContainer.query(CommandContainer.java:73)
	at org.h2.command.Command.executeQueryLocal(Command.java:71)
	at org.h2.command.Command.executeQuery(Command.java:60)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:67)
	at zigen.plugin.db.core.TableManager.invoke(TableManager.java:71)
	at zigen.plugin.db.core.TableManager.invoke(TableManager.java:47)
	at zigen.plugin.db.core.TableManager.invoke(TableManager.java:40)
	at zigen.plugin.db.ui.editors.TableViewEditor.update(TableViewEditor.java:657)
	at zigen.plugin.db.ui.actions.OpenEditorAction.openTableEditor(OpenEditorAction.java:109)
	at zigen.plugin.db.ui.actions.OpenEditorAction.run(OpenEditorAction.java:72)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:499)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:539)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:488)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:66)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:928)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3348)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:2968)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:1914)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:1878)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:419)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.IDEApplication.run(IDEApplication.java:95)
	at org.eclipse.core.internal.runtime.PlatformActivator$1.run(PlatformActivator.java:78)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:92)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:68)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.core.launcher.Main.invokeFramework(Main.java:336)
	at org.eclipse.core.launcher.Main.basicRun(Main.java:280)
	at org.eclipse.core.launcher.Main.run(Main.java:977)
	at org.eclipse.core.launcher.Main.main(Main.java:952)
01-28 01:29:07 database: opening C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\selj\startup\db\sel
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-34]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:136)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:95)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:85)
	at org.seasar.extension.dbcp.impl.ConnectionPoolImpl.createConnection(ConnectionPoolImpl.java:200)
	at org.seasar.extension.dbcp.impl.ConnectionPoolImpl.checkOut(ConnectionPoolImpl.java:162)
	at org.seasar.extension.dbcp.impl.DataSourceImpl.getConnection(DataSourceImpl.java:46)
	at org.seasar.extension.jdbc.util.DataSourceUtil.getConnection(DataSourceUtil.java:36)
	at org.seasar.dao.impl.DaoMetaDataImpl.initialize(DaoMetaDataImpl.java:191)
	at org.seasar.dao.impl.DaoMetaDataFactoryImpl.createDaoMetaData(DaoMetaDataFactoryImpl.java:140)
	at org.seasar.dao.impl.DaoMetaDataFactoryImpl.getDaoMetaData(DaoMetaDataFactoryImpl.java:109)
	at org.seasar.dao.interceptors.S2DaoInterceptor.invoke(S2DaoInterceptor.java:51)
	at sel.dao.DocDao$$EnhancedByS2AOP$$1ea0252$$MethodInvocation$$findByDocTypeId0.proceed(MethodInvocationClassGenerator.java)
	at sel.dao.DocDao$$EnhancedByS2AOP$$1ea0252.findByDocTypeId(DocDao$$EnhancedByS2AOP$$1ea0252.java)
	at sel.model.DocModel.initialize(DocModel.java:53)
	at sel.view.MainView.setup(MainView.java:1400)
	at sel.Main.newMainView(Main.java:23)
	at sel.Main$2.execute(Main.java:57)
	at sel.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
01-28 01:30:29 database: opening C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\selj\startup\db\sel
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-34]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:136)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at zigen.plugin.db.core.ConnectionManager.getConnection(ConnectionManager.java:51)
	at zigen.plugin.db.ui.actions.ConnectDBAction.run(ConnectDBAction.java:70)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:499)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:539)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:488)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:66)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:928)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3348)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:2968)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:1914)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:1878)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:419)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.IDEApplication.run(IDEApplication.java:95)
	at org.eclipse.core.internal.runtime.PlatformActivator$1.run(PlatformActivator.java:78)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:92)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:68)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.core.launcher.Main.invokeFramework(Main.java:336)
	at org.eclipse.core.launcher.Main.basicRun(Main.java:280)
	at org.eclipse.core.launcher.Main.run(Main.java:977)
	at org.eclipse.core.launcher.Main.main(Main.java:952)
01-28 01:31:23 database: opening C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\selj\startup\db\sel
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-34]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:136)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:95)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:85)
	at org.seasar.extension.dbcp.impl.ConnectionPoolImpl.createConnection(ConnectionPoolImpl.java:200)
	at org.seasar.extension.dbcp.impl.ConnectionPoolImpl.checkOut(ConnectionPoolImpl.java:162)
	at org.seasar.extension.dbcp.impl.DataSourceImpl.getConnection(DataSourceImpl.java:46)
	at org.seasar.extension.jdbc.util.DataSourceUtil.getConnection(DataSourceUtil.java:36)
	at org.seasar.dao.impl.DaoMetaDataImpl.initialize(DaoMetaDataImpl.java:191)
	at org.seasar.dao.impl.DaoMetaDataFactoryImpl.createDaoMetaData(DaoMetaDataFactoryImpl.java:140)
	at org.seasar.dao.impl.DaoMetaDataFactoryImpl.getDaoMetaData(DaoMetaDataFactoryImpl.java:109)
	at org.seasar.dao.interceptors.S2DaoInterceptor.invoke(S2DaoInterceptor.java:51)
	at sel.dao.DocDao$$EnhancedByS2AOP$$1ea0252$$MethodInvocation$$findByDocTypeId0.proceed(MethodInvocationClassGenerator.java)
	at sel.dao.DocDao$$EnhancedByS2AOP$$1ea0252.findByDocTypeId(DocDao$$EnhancedByS2AOP$$1ea0252.java)
	at sel.model.DocModel.initialize(DocModel.java:53)
	at sel.view.MainView.setup(MainView.java:1400)
	at sel.Main.newMainView(Main.java:23)
	at sel.Main$2.execute(Main.java:57)
	at sel.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
02-05 21:44:51 database: opening C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\Zeeta\startup\db\sel
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-34]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:136)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:95)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:85)
	at org.seasar.extension.dbcp.impl.ConnectionPoolImpl.createConnection(ConnectionPoolImpl.java:200)
	at org.seasar.extension.dbcp.impl.ConnectionPoolImpl.checkOut(ConnectionPoolImpl.java:162)
	at org.seasar.extension.dbcp.impl.DataSourceImpl.getConnection(DataSourceImpl.java:46)
	at org.seasar.extension.jdbc.util.DataSourceUtil.getConnection(DataSourceUtil.java:36)
	at org.seasar.dao.impl.DaoMetaDataImpl.initialize(DaoMetaDataImpl.java:191)
	at org.seasar.dao.impl.DaoMetaDataFactoryImpl.createDaoMetaData(DaoMetaDataFactoryImpl.java:140)
	at org.seasar.dao.impl.DaoMetaDataFactoryImpl.getDaoMetaData(DaoMetaDataFactoryImpl.java:109)
	at org.seasar.dao.interceptors.S2DaoInterceptor.invoke(S2DaoInterceptor.java:51)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$3e89c3$$MethodInvocation$$findByDocTypeId0.proceed(MethodInvocationClassGenerator.java)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$3e89c3.findByDocTypeId(DocDao$$EnhancedByS2AOP$$3e89c3.java)
	at jp.tokyo.selj.model.DocModel.initialize(DocModel.java:107)
	at jp.tokyo.selj.view.FrmZeetaMain.setup(FrmZeetaMain.java:1449)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:24)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:60)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
03-23 22:57:38 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table WORK not found; SQL statement: select *, workCount from doc ,(select count(*) as workCount from work where work.docid=?) where doc.docid=? [42S02-34]
	at org.h2.message.Message.addSQL(Message.java:341)
	at org.h2.command.Parser.parse(Parser.java:224)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:169)
	at org.h2.engine.Session.prepareCommand(Session.java:151)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:1203)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:158)
	at org.seasar.extension.dbcp.impl.ConnectionWrapperImpl.prepareStatement(ConnectionWrapperImpl.java:140)
	at org.seasar.extension.jdbc.util.ConnectionUtil.prepareStatement(ConnectionUtil.java:50)
	at org.seasar.extension.jdbc.impl.BasicStatementFactory.createPreparedStatement(BasicStatementFactory.java:34)
	at org.seasar.extension.jdbc.impl.BasicHandler.prepareStatement(BasicHandler.java:95)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.prepareStatement(BasicSelectHandler.java:146)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:131)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:120)
	at org.seasar.dao.impl.SelectDynamicCommand.execute(SelectDynamicCommand.java:55)
	at org.seasar.dao.interceptors.S2DaoInterceptor.invoke(S2DaoInterceptor.java:53)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$134f69a$$MethodInvocation$$findByDocId1.proceed(MethodInvocationClassGenerator.java)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$134f69a.findByDocId(DocDao$$EnhancedByS2AOP$$134f69a.java)
	at jp.tokyo.selj.model.DocModel.initialize(DocModel.java:119)
	at jp.tokyo.selj.view.FrmZeetaMain.setup(FrmZeetaMain.java:1606)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:24)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:60)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
org.h2.jdbc.JdbcSQLException: Table WORK not found [42S02-34]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.schema.Schema.getTableOrView(Schema.java:199)
	at org.h2.command.Parser.readTableFilter(Parser.java:743)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1213)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1280)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1207)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1094)
	at org.h2.command.Parser.parseQueryWithParams(Parser.java:1082)
	at org.h2.command.Parser.readTableFilter(Parser.java:714)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1213)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1280)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1207)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1094)
	at org.h2.command.Parser.parseSelect(Parser.java:1075)
	at org.h2.command.Parser.parse(Parser.java:332)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:169)
	at org.h2.engine.Session.prepareCommand(Session.java:151)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:1203)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:158)
	at org.seasar.extension.dbcp.impl.ConnectionWrapperImpl.prepareStatement(ConnectionWrapperImpl.java:140)
	at org.seasar.extension.jdbc.util.ConnectionUtil.prepareStatement(ConnectionUtil.java:50)
	at org.seasar.extension.jdbc.impl.BasicStatementFactory.createPreparedStatement(BasicStatementFactory.java:34)
	at org.seasar.extension.jdbc.impl.BasicHandler.prepareStatement(BasicHandler.java:95)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.prepareStatement(BasicSelectHandler.java:146)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:131)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:120)
	at org.seasar.dao.impl.SelectDynamicCommand.execute(SelectDynamicCommand.java:55)
	at org.seasar.dao.interceptors.S2DaoInterceptor.invoke(S2DaoInterceptor.java:53)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$134f69a$$MethodInvocation$$findByDocId1.proceed(MethodInvocationClassGenerator.java)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$134f69a.findByDocId(DocDao$$EnhancedByS2AOP$$134f69a.java)
	at jp.tokyo.selj.model.DocModel.initialize(DocModel.java:119)
	at jp.tokyo.selj.view.FrmZeetaMain.setup(FrmZeetaMain.java:1606)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:24)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:60)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
03-23 22:59:45 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table WORK not found; SQL statement: select *, workCount from doc ,(select count(*) as workCount from work where work.docid=?) where doc.docid=? [42S02-34]
	at org.h2.message.Message.addSQL(Message.java:341)
	at org.h2.command.Parser.parse(Parser.java:224)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:169)
	at org.h2.engine.Session.prepareCommand(Session.java:151)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:1203)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:158)
	at org.seasar.extension.dbcp.impl.ConnectionWrapperImpl.prepareStatement(ConnectionWrapperImpl.java:140)
	at org.seasar.extension.jdbc.util.ConnectionUtil.prepareStatement(ConnectionUtil.java:50)
	at org.seasar.extension.jdbc.impl.BasicStatementFactory.createPreparedStatement(BasicStatementFactory.java:34)
	at org.seasar.extension.jdbc.impl.BasicHandler.prepareStatement(BasicHandler.java:95)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.prepareStatement(BasicSelectHandler.java:146)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:131)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:120)
	at org.seasar.dao.impl.SelectDynamicCommand.execute(SelectDynamicCommand.java:55)
	at org.seasar.dao.interceptors.S2DaoInterceptor.invoke(S2DaoInterceptor.java:53)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$a4e2e3$$MethodInvocation$$findByDocId1.proceed(MethodInvocationClassGenerator.java)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$a4e2e3.findByDocId(DocDao$$EnhancedByS2AOP$$a4e2e3.java)
	at jp.tokyo.selj.model.DocModel.initialize(DocModel.java:119)
	at jp.tokyo.selj.view.FrmZeetaMain.setup(FrmZeetaMain.java:1606)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:24)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:60)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
org.h2.jdbc.JdbcSQLException: Table WORK not found [42S02-34]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.schema.Schema.getTableOrView(Schema.java:199)
	at org.h2.command.Parser.readTableFilter(Parser.java:743)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1213)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1280)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1207)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1094)
	at org.h2.command.Parser.parseQueryWithParams(Parser.java:1082)
	at org.h2.command.Parser.readTableFilter(Parser.java:714)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1213)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1280)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1207)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1094)
	at org.h2.command.Parser.parseSelect(Parser.java:1075)
	at org.h2.command.Parser.parse(Parser.java:332)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:169)
	at org.h2.engine.Session.prepareCommand(Session.java:151)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:1203)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:158)
	at org.seasar.extension.dbcp.impl.ConnectionWrapperImpl.prepareStatement(ConnectionWrapperImpl.java:140)
	at org.seasar.extension.jdbc.util.ConnectionUtil.prepareStatement(ConnectionUtil.java:50)
	at org.seasar.extension.jdbc.impl.BasicStatementFactory.createPreparedStatement(BasicStatementFactory.java:34)
	at org.seasar.extension.jdbc.impl.BasicHandler.prepareStatement(BasicHandler.java:95)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.prepareStatement(BasicSelectHandler.java:146)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:131)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:120)
	at org.seasar.dao.impl.SelectDynamicCommand.execute(SelectDynamicCommand.java:55)
	at org.seasar.dao.interceptors.S2DaoInterceptor.invoke(S2DaoInterceptor.java:53)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$a4e2e3$$MethodInvocation$$findByDocId1.proceed(MethodInvocationClassGenerator.java)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$a4e2e3.findByDocId(DocDao$$EnhancedByS2AOP$$a4e2e3.java)
	at jp.tokyo.selj.model.DocModel.initialize(DocModel.java:119)
	at jp.tokyo.selj.view.FrmZeetaMain.setup(FrmZeetaMain.java:1606)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:24)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:60)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
03-23 23:16:47 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Table WORK not found; SQL statement: select * from work [42S02-34]
	at org.h2.message.Message.addSQL(Message.java:341)
	at org.h2.command.Parser.parse(Parser.java:224)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:169)
	at org.h2.engine.Session.prepareCommand(Session.java:151)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at jp.tokyo.selj.view.FrmZeetaMain.versionCheck(FrmZeetaMain.java:1609)
	at jp.tokyo.selj.view.FrmZeetaMain.setup(FrmZeetaMain.java:1626)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:24)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:60)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
org.h2.jdbc.JdbcSQLException: Table WORK not found [42S02-34]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.schema.Schema.getTableOrView(Schema.java:199)
	at org.h2.command.Parser.readTableFilter(Parser.java:743)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1213)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1280)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1207)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1094)
	at org.h2.command.Parser.parseSelect(Parser.java:1075)
	at org.h2.command.Parser.parse(Parser.java:332)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:169)
	at org.h2.engine.Session.prepareCommand(Session.java:151)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at jp.tokyo.selj.view.FrmZeetaMain.versionCheck(FrmZeetaMain.java:1609)
	at jp.tokyo.selj.view.FrmZeetaMain.setup(FrmZeetaMain.java:1626)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:24)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:60)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
04-04 09:09:29 database: opening C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\Zeeta\startup\db\sel
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-44]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:425)
	at org.h2.engine.Database.<init>(Database.java:383)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:141)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:950)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:95)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:85)
	at jp.tokyo.selj.ZeetaMain.versionCheck(ZeetaMain.java:44)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:32)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:93)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
04-04 09:09:31 database: opening C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\Zeeta\startup\db\sel
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-44]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:425)
	at org.h2.engine.Database.<init>(Database.java:383)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:141)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:950)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:95)
	at org.seasar.extension.dbcp.impl.XADataSourceImpl.getXAConnection(XADataSourceImpl.java:85)
	at org.seasar.extension.dbcp.impl.ConnectionPoolImpl.createConnection(ConnectionPoolImpl.java:200)
	at org.seasar.extension.dbcp.impl.ConnectionPoolImpl.checkOut(ConnectionPoolImpl.java:162)
	at org.seasar.extension.dbcp.impl.DataSourceImpl.getConnection(DataSourceImpl.java:46)
	at org.seasar.extension.jdbc.util.DataSourceUtil.getConnection(DataSourceUtil.java:36)
	at org.seasar.dao.impl.DaoMetaDataImpl.initialize(DaoMetaDataImpl.java:191)
	at org.seasar.dao.impl.DaoMetaDataFactoryImpl.createDaoMetaData(DaoMetaDataFactoryImpl.java:140)
	at org.seasar.dao.impl.DaoMetaDataFactoryImpl.getDaoMetaData(DaoMetaDataFactoryImpl.java:109)
	at org.seasar.dao.interceptors.S2DaoInterceptor.invoke(S2DaoInterceptor.java:51)
	at jp.tokyo.selj.dao.OutputTypeDao$$EnhancedByS2AOP$$10a6ae2$$MethodInvocation$$findAll1.proceed(MethodInvocationClassGenerator.java)
	at jp.tokyo.selj.dao.OutputTypeDao$$EnhancedByS2AOP$$10a6ae2.findAll(OutputTypeDao$$EnhancedByS2AOP$$10a6ae2.java)
	at jp.tokyo.selj.model.MasterComboModel.refreshOutputType(MasterComboModel.java:57)
	at jp.tokyo.selj.model.MasterComboModel.newOutputTypeComboBoxModel(MasterComboModel.java:62)
	at jp.tokyo.selj.view.PnlOutputDetail.setup(PnlOutputDetail.java:56)
	at jp.tokyo.selj.view.DlgOutputDetail.setup(DlgOutputDetail.java:148)
	at jp.tokyo.selj.view.DlgOutputList$ActUseOutputDetail.<init>(DlgOutputList.java:102)
	at jp.tokyo.selj.view.DlgOutputList$ActNewOutput.<init>(DlgOutputList.java:108)
	at jp.tokyo.selj.view.DlgOutputList.setup(DlgOutputList.java:222)
	at jp.tokyo.selj.view.FrmZeetaMain$ActShowOutputListForWork.getDlgOutputList(FrmZeetaMain.java:850)
	at jp.tokyo.selj.view.FrmZeetaMain$ActShowOutputListForWork.<init>(FrmZeetaMain.java:828)
	at jp.tokyo.selj.view.FrmZeetaMain.<init>(FrmZeetaMain.java:1594)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:34)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:93)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
05-27 02:17:56 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table SYSZEETA not found; SQL statement: select * from sysZeeta where id=1 [42S02-44]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:226)
	at org.h2.command.Parser.prepareCommand(Parser.java:191)
	at org.h2.engine.Session.prepareLocal(Session.java:174)
	at org.h2.engine.Session.prepareCommand(Session.java:156)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:993)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at jp.tokyo.selj.ZeetaDBManager.getVersion(ZeetaDBManager.java:275)
	at jp.tokyo.selj.ZeetaDBManager.check(ZeetaDBManager.java:244)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:29)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:67)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
org.h2.jdbc.JdbcSQLException: Table SYSZEETA not found [42S02-44]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:199)
	at org.h2.command.Parser.readTableFilter(Parser.java:764)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1208)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1301)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1202)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1089)
	at org.h2.command.Parser.parseSelect(Parser.java:1070)
	at org.h2.command.Parser.parse(Parser.java:339)
	at org.h2.command.Parser.parse(Parser.java:220)
	at org.h2.command.Parser.prepareCommand(Parser.java:191)
	at org.h2.engine.Session.prepareLocal(Session.java:174)
	at org.h2.engine.Session.prepareCommand(Session.java:156)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:993)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at jp.tokyo.selj.ZeetaDBManager.getVersion(ZeetaDBManager.java:275)
	at jp.tokyo.selj.ZeetaDBManager.check(ZeetaDBManager.java:244)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:29)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:67)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
09-05 00:10:12 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: 一般エラー: java.lang.Error: File ID mismatch got=0 expected=31 pos=752 true org.h2.store.DiskFile:C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\Zeeta\startup\db\sel.data.db blockCount:0
General error: java.lang.Error: File ID mismatch got=0 expected=31 pos=752 true org.h2.store.DiskFile:C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\Zeeta\startup\db\sel.data.db blockCount:0 [50000-66]
	at org.h2.message.Message.getSQLException(Message.java:89)
	at org.h2.message.Message.convert(Message.java:174)
	at org.h2.command.Command.executeQueryLocal(Command.java:120)
	at org.h2.command.Command.executeQuery(Command.java:106)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:89)
	at org.seasar.extension.jdbc.impl.PreparedStatementWrapper.executeQuery(PreparedStatementWrapper.java:81)
	at org.seasar.framework.util.PreparedStatementUtil.executeQuery(PreparedStatementUtil.java:46)
	at org.seasar.extension.jdbc.impl.BasicResultSetFactory.createResultSet(BasicResultSetFactory.java:44)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.createResultSet(BasicSelectHandler.java:281)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:257)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:210)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:184)
	at org.seasar.dao.impl.SelectDynamicCommand.execute(SelectDynamicCommand.java:69)
	at org.seasar.dao.interceptors.S2DaoInterceptor.invoke(S2DaoInterceptor.java:53)
	at org.seasar.dao.pager.PagerS2DaoInterceptorWrapper.invoke(PagerS2DaoInterceptorWrapper.java:71)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$3820e$$MethodInvocation$$findByDocTypeId0.proceed(MethodInvocationClassGenerator.java)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$3820e.findByDocTypeId(DocDao$$EnhancedByS2AOP$$3820e.java)
	at jp.tokyo.selj.model.DocModel.initialize(DocModel.java:146)
	at jp.tokyo.selj.view.FrmZeetaMain.setup(FrmZeetaMain.java:2053)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:34)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:69)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.Error: File ID mismatch got=0 expected=31 pos=752 true org.h2.store.DiskFile:C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\Zeeta\startup\db\sel.data.db blockCount:0
	at org.h2.message.Message.getInternalError(Message.java:126)
	at org.h2.store.DiskFile.getRecord(DiskFile.java:456)
	at org.h2.store.Storage.getRecord(Storage.java:65)
	at org.h2.index.ScanIndex.getNextRow(ScanIndex.java:237)
	at org.h2.index.ScanCursor.next(ScanCursor.java:69)
	at org.h2.table.TableFilter.next(TableFilter.java:247)
	at org.h2.command.dml.Select.queryFlat(Select.java:322)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:386)
	at org.h2.command.dml.Query.query(Query.java:227)
	at org.h2.command.CommandContainer.query(CommandContainer.java:77)
	at org.h2.command.Command.executeQueryLocal(Command.java:118)
	... 26 more
09-05 00:32:08 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: 一般エラー: java.lang.Error: File ID mismatch got=0 expected=31 pos=752 true org.h2.store.DiskFile:C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\Zeeta\startup\db\sel.data.db blockCount:0
General error: java.lang.Error: File ID mismatch got=0 expected=31 pos=752 true org.h2.store.DiskFile:C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\Zeeta\startup\db\sel.data.db blockCount:0 [50000-66]
	at org.h2.message.Message.getSQLException(Message.java:89)
	at org.h2.message.Message.convert(Message.java:174)
	at org.h2.command.Command.executeQueryLocal(Command.java:120)
	at org.h2.command.Command.executeQuery(Command.java:106)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:89)
	at org.seasar.extension.jdbc.impl.PreparedStatementWrapper.executeQuery(PreparedStatementWrapper.java:81)
	at org.seasar.framework.util.PreparedStatementUtil.executeQuery(PreparedStatementUtil.java:46)
	at org.seasar.extension.jdbc.impl.BasicResultSetFactory.createResultSet(BasicResultSetFactory.java:44)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.createResultSet(BasicSelectHandler.java:281)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:257)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:210)
	at org.seasar.extension.jdbc.impl.BasicSelectHandler.execute(BasicSelectHandler.java:184)
	at org.seasar.dao.impl.SelectDynamicCommand.execute(SelectDynamicCommand.java:69)
	at org.seasar.dao.interceptors.S2DaoInterceptor.invoke(S2DaoInterceptor.java:53)
	at org.seasar.dao.pager.PagerS2DaoInterceptorWrapper.invoke(PagerS2DaoInterceptorWrapper.java:71)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$3820e$$MethodInvocation$$findByDocTypeId0.proceed(MethodInvocationClassGenerator.java)
	at jp.tokyo.selj.dao.DocDao$$EnhancedByS2AOP$$3820e.findByDocTypeId(DocDao$$EnhancedByS2AOP$$3820e.java)
	at jp.tokyo.selj.model.DocModel.initialize(DocModel.java:146)
	at jp.tokyo.selj.view.FrmZeetaMain.setup(FrmZeetaMain.java:2053)
	at jp.tokyo.selj.ZeetaMain.newMainView(ZeetaMain.java:34)
	at jp.tokyo.selj.ZeetaMain$2.execute(ZeetaMain.java:69)
	at jp.tokyo.selj.Splash$2.run(Splash.java:31)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.Error: File ID mismatch got=0 expected=31 pos=752 true org.h2.store.DiskFile:C:\Documents and Settings\mikami\My Documents\project\javaWork\selj\release\Zeeta\startup\db\sel.data.db blockCount:0
	at org.h2.message.Message.getInternalError(Message.java:126)
	at org.h2.store.DiskFile.getRecord(DiskFile.java:456)
	at org.h2.store.Storage.getRecord(Storage.java:65)
	at org.h2.index.ScanIndex.getNextRow(ScanIndex.java:237)
	at org.h2.index.ScanCursor.next(ScanCursor.java:69)
	at org.h2.table.TableFilter.next(TableFilter.java:247)
	at org.h2.command.dml.Select.queryFlat(Select.java:322)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:386)
	at org.h2.command.dml.Query.query(Query.java:227)
	at org.h2.command.CommandContainer.query(CommandContainer.java:77)
	at org.h2.command.Command.executeQueryLocal(Command.java:118)
	... 26 more
